### ISSUE TITLE
Implement ID validator for Belgium  🇧🇪

### ISSUE THREAD

**Issue by YvesBos** [reducktion/socrates-java#32]
Information on the Belgian National Register Number can be found [here](https://en.wikipedia.org/wiki/National_identification_number#Belgium) and [here (dutch)](http://www.ibz.rrn.fgov.be/fileadmin/user_upload/nl/rr/instructies/IT-lijst/IT000_Rijksregisternummer.pdf).

**Comment by YvesBos** [comment]
I'd like to work on the implementation, can you assign me? :)

**Comment by SLourenco** [comment]
Assigned the issue to you @YvesBos. You can also create a PR on the [PHP repo ](https://github.com/reducktion/socrates/issues/58) to add the links to the official documentation, if you feel so inclined
