### ISSUE TITLE
[Question] Will Citizen support returning the date of birth as a Java date object?

### ISSUE THREAD

**Issue by AlexOlival** [reducktion/socrates-java#40]
I've noticed that `Citizen` allows the user to get the date of birth separately as compound data:

https://github.com/reducktion/socrates-java/blob/9da406fe1974c17c24ec49299bf73039a46bf3fd/src/main/java/com/github/reducktion/socrates/extractor/Citizen.java#L21-L31

Will there be a method to return a Java date object? If not, why?
I'm about to do some changes to the dob handling over in PHP land (ungluing ourselves to a DateTime package) so I'm interested in knowing this.

**Comment by afbernardino** [comment]
I won't say that this is set in stone, but the reason behind it is that some IDs do not provide the information about the day of birth (e.g. IDs in France).

We could return a `LocalDate` object, but (in the case above) the day of birth would always be the same, which might be misleading to the user.

One could argue that we could return an `YearMonth` object, but we would still have to support a `LocalDate` object for the IDs that do provide information about the day of birth, so it would still be misleading and (I think) even confusing to the user.

Another option would be to create a new object (e.g. `DateOfBirth`), but given the amount of fields that we have and the mapping that we would have to do (i.e. we would have to deal with the `Optional`), I thought that this would be a good approach.

Hope I answered your question!

**Comment by AlexOlival** [comment]
I see :eyes: .
With France, what we do is return a `DateTime` (technically a `Carbon`) object formatted to whatever date info is returned:

```php
private function getDateOfBirth(string $id): Carbon
{
    $dateDigits = substr($id, 1, 4);
    [$year, $month] = str_split($dateDigits, 2);
    $currentYear = now()->format('y');

    $year = $year > $currentYear ? $year + 1900 : $year + 2000;

    if ($month > 0 && $month < 13) {
        return Carbon::createFromFormat('Y-m', "$year-$month");
    }

    if ($month > 30 && $month < 43) {
        $month -= 30;
        return Carbon::createFromFormat('Y-m', "$year-$month");
    }

    return Carbon::createFromFormat('Y', $year);
}
```

But I definitely see what you mean. I'll weigh this in - most likely I'll keep a method returning a `DateTime` instance, and add those three to complement them. Thanks! :+1:
