### ISSUE TITLE
Denmark date of birth century

### ISSUE THREAD

**Issue by AlexOlival** [reducktion/socrates-java#42]
In the Denmark extractor, the year is extracted like so:

https://github.com/reducktion/socrates-java/blob/44623316fcda5b10adac93e3c1c99480aff1fa6c/src/main/java/com/github/reducktion/socrates/extractor/DenmarkCitizenExtractor.java#L41-L46

However, it's a bit more complicated than that. As with many other countries we implemented, they have a way to determine what _century_ the date is from. In this case, another digit from the ID is taken into account. Here's the PHP version:

```php
$year = $twoDigitYear < 70
        ? Carbon::createFromFormat('Y', "19$twoDigitYear")->format('Y') // concatenating 19 + the two digits
        : Carbon::createFromFormat('y', (string) $twoDigitYear)->format('Y');


if (($seventhDigit === 4 || $seventhDigit === 9) && $year <= 1936) {
        $year += 100;
} elseif ($seventhDigit > 4) {
        $year > 1957 ? $year -= 100 : $year += 100;
}
```

This is not the only country that handles two digit format years like that - you can go ahead and check how we handled those in the PHP package, as we made sure to cover all these cases in tests as well 👍

**Comment by afbernardino** [comment]
I investigated the topic a bit further and it seems that we are missing that validation indeed.
I'll take a look at it!
Thanks! 👍

**Comment by afbernardino** [comment]
Just re-read the article in [wikipedia](https://en.wikipedia.org/wiki/Personal_identification_number_(Denmark)) and noticed that for IDs issued after 2007 the check digit validation might fail, but the ID can still be valid.

> since October 2007 personal identification numbers do not always validate using the check digit.

Maybe we should drop it entirely 🤔

Ideas?

**Comment by AlexOlival** [comment]
> Just re-read the article in [wikipedia](https://en.wikipedia.org/wiki/Personal_identification_number_(Denmark)) and noticed that for IDs issued after 2007 the check digit validation might fail, but the ID can still be valid.
> 
> 
> 
> > since October 2007 personal identification numbers do not always validate using the check digit.
> 
> 
> 
> Maybe we should drop it entirely 🤔
> 
> 
> 
> Thoughts?

This was something that some danish people confirmed as well and is a limitation of their system . However, we are still to find a CPR with that problem. The chances of extracting the wrong year based on a two digit format are way higher. In my opinion it's well worth the risk.

**Comment by afbernardino** [comment]
I think we should keep the date validation. I was wondering about the check digit, do you think we should keep it as well? Have you had problems with it?

**Comment by AlexOlival** [comment]
So far we haven't. The socrates-php algorithm was adapted from a JS package which me and @SLourenco use on the front end of the application we both work in (and it requires high availability and accuracy for its use case) and it has the check digit working fine so far :thinking:

**Comment by afbernardino** [comment]
Very well! Let's leave as it is right now then and re-evaluate if necessary.
